//console.log( "Look at me!" );

/*
var wrapper = document.createElement( "div" );
wrapper.className = "tabbar-wrapper";
var tabbar = document.createElement( "ul" );
tabbar.className = "tabbar list-inline visible-lg visible-md visible-sm hidden-xs";
var menuitem = document.createElement( "li" );
var tabs = document.createElement( "ul" );
tabs.className = "tabs flex-nav";
tabs.role = "menu";
var tab0 = document.createElement( "li" );
tab0.role = "presentation";
tab0.id = "all-stores";
var tab2 = document.createElement( "li" );
tab2.role = "presentation";
tab2.id = "my-store";
var tab3 = document.createElement( "li" );
tab3.role = "presentation";
tab3.id = "new-product";
var tab4 = document.createElement( "li" );
tab4.role = "presentation";
tab4.id = "wallet";
var link0 = document.createElement( "a" );
link0.role = "menuitem";
link0.href = "/store/";
link0.title = "View all stores";
link0.innerText = "All stores";
var link2 = document.createElement( "a" );
link2.role = "menuitem";
link2.href = "/store/my-store/";
link2.title = "View and manage your store";
link2.innerText = "My store";
var link3 = document.createElement( "a" );
link3.role = "menuitem";
link3.href = "/store/new-product/";
link3.title = "Create a new product";
link3.innerText = "New product";
var link4 = document.createElement( "a" );
link4.role = "menuitem";
link4.href = "/store/wallet/";
link4.title = "View your bitcoin wallet";
link4.innerText = "Wallet";
tab0.append( link0 );
tab2.append( link2 );
tab3.append( link3 );
tab4.append( link4 );
tabs.append( tab0 );
tabs.append( tab2 );
tabs.append( tab3 );
tabs.append( tab4 );
menuitem.append( tabs );
tabbar.append( menuitem );
wrapper.append( tabbar );
document.getElementById( "tabmenu" ).append( wrapper );
*/
